# Generated by Django 2.2.14 on 2020-08-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authort',
            new_name='author',
        ),
    ]
